
from enum import Enum


class RewardStrategy(Enum):
    REWARD_ALL_ITEMS_PACKED = 0
    REWARD_COMPACTNESS = 1
    REWARD_EACH_ITEM_PACKED = 2
    REWARD_EACH_ITEM_PACKED_COMPACTNESS = 3
    REWARD_EACH_ITEM_PACKED_HEIGHT = 4

    NEGATIVE_REWARD_PACKING_FAILED = 20
