
from enum import Enum


class RewardStrategy(Enum):
    REWARD_ALL_ITEMS_PACKED = 0
    REWARD_COMPACTNESS = 1
    REWARD_EACH_ITEM_PACKED = 2
    REWARD_EACH_ITEM_PACKED_COMPACTNESS = 3
    REWARD_EACH_ITEM_PACKED_HEIGHT = 4

    PENALIZE_EACH_ITEM_DISTANCE_COG = 100
    PENALIZE_EACH_ITEM_PACKING_FAILED = 101
    PENALIZE_PACKING_FAILED = 102
