
from enum import Enum


class RewardStrategy(Enum):
    REWARD_ALL_PACKED = 0
    REWARD_ALL_COMPACTNESS = 1

    REWARD_EACH_PACKED = 10
    REWARD_EACH_COMPACTNESS = 11
    REWARD_EACH_HEIGHT_CHANGE = 12

    PENALIZE_ALL_PACKING_FAILED = 101

    PENALIZE_EACH_DISTANCE_COG = 110
    PENALIZE_EACH_PACKED_HEIGHT = 111
    PENALIZE_EACH_PACKING_FAILED = 112
    PENALIZE_EACH_DISTANCE_NEXT_ITEM = 113
